version: '3.9'

services:
  db:
    image: postgres:16
    container_name: transaction-db
    restart: always
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg123
      POSTGRES_DB: transaction
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: transaction-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=transaction;Username=pg;Password=pg123"
    ports:
      - "5000:8080"
    command: >
      bash -c "dotnet ef database update && dotnet TransactionProcessor.dll"

volumes:
  pgdata:
